name: pubsub
version: 0.0.2-dev
author: Oliver Lietz <info@oliverlietz.de>
description: publish/subscribe message bus
homepage: https://github.com/oliverlietz/pubsub
dependencies:
  logging: ^0.11.1+1
  uuid: ^0.5.0
dev_dependencies:
  test: ^0.12.4+7
